"""doc

Revision ID: 553b604ac90b
Revises: a7d6cf147b07
Create Date: 2020-05-08 21:50:49.683033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553b604ac90b'
down_revision = 'a7d6cf147b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'car_id', 'part_id')
    )
    op.create_index(op.f('ix_doc_car_id'), 'doc', ['car_id'], unique=False)
    op.create_index(op.f('ix_doc_creator_id'), 'doc', ['creator_id'], unique=False)
    op.create_index(op.f('ix_doc_part_id'), 'doc', ['part_id'], unique=False)
    op.create_index(op.f('ix_doc_slug'), 'doc', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_slug'), table_name='doc')
    op.drop_index(op.f('ix_doc_part_id'), table_name='doc')
    op.drop_index(op.f('ix_doc_creator_id'), table_name='doc')
    op.drop_index(op.f('ix_doc_car_id'), table_name='doc')
    op.drop_table('doc')
    # ### end Alembic commands ###
