"""car, part, doc

Revision ID: a7d6cf147b07
Revises: 76bba23d9896
Create Date: 2020-05-05 17:03:35.638128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d6cf147b07'
down_revision = '76bba23d9896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('img_src', sa.String(length=255), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'car_id', 'part_id')
    )
    op.create_index(op.f('ix_doc_car_id'), 'doc', ['car_id'], unique=False)
    op.create_index(op.f('ix_doc_creator_id'), 'doc', ['creator_id'], unique=False)
    op.create_index(op.f('ix_doc_part_id'), 'doc', ['part_id'], unique=False)
    op.create_index(op.f('ix_doc_slug'), 'doc', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_slug'), table_name='doc')
    op.drop_index(op.f('ix_doc_part_id'), table_name='doc')
    op.drop_index(op.f('ix_doc_creator_id'), table_name='doc')
    op.drop_index(op.f('ix_doc_car_id'), table_name='doc')
    op.drop_table('doc')
    op.drop_table('car')
    op.drop_table('part')
    # ### end Alembic commands ###
